{{/* helm/microservices/templates/serviceaccount.yaml */}}
{{- range $name, $svc := .Values.services }}
{{- if $svc.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ $name }}-service
  namespace: {{ $.Values.global.namespace }}
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::ACCOUNT_ID:role/ms-reto4-{{ $.Values.global.environment }}-{{ $name }}-irsa
{{- end }}
{{- end }}

---
{{/* Ingress */}}
{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: microservices-ingress
  namespace: {{ .Values.global.namespace }}
  annotations:
    {{- range $k, $v := .Values.ingress.annotations }}
    {{ $k }}: {{ $v | quote }}
    {{- end }}
    alb.ingress.kubernetes.io/scheme: {{ .Values.ingress.scheme }}
spec:
  rules:
    - http:
        paths:
          {{- range $name, $svc := .Values.services }}
          {{- if $svc.enabled }}
          - path: /{{ $name }}s
            pathType: Prefix
            backend:
              service:
                name: {{ $name }}-service
                port:
                  number: {{ $svc.port }}
          {{- end }}
          {{- end }}
          - path: /auth
            pathType: Prefix
            backend:
              service:
                name: auth-service
                port:
                  number: 8080
{{- end }}
