#cloud-config
package_update: true
packages:
  - docker.io
  - git
runcmd:
  - systemctl enable --now docker
  - usermod -aG docker opc
  - mkdir -p /opt/santos-pegasus
  - chown opc:opc /opt/santos-pegasus
final_message: "Servidor OCI preparado para Docker."
