--
-- PostgreSQL database dump
--

\restrict qxITwQbuQFgGZY0a082R5ddrVe9JAgLq6sxm0WXdEDmHTaNDaG3NJVOaja5r422

-- Dumped from database version 18.1
-- Dumped by pg_dump version 18.1

-- Started on 2025-12-08 07:25:32

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET transaction_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- TOC entry 220 (class 1259 OID 16390)
-- Name: autores; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.autores (
    id bigint NOT NULL,
    fallecimiento integer,
    nacimiento integer,
    nombre character varying(255)
);


ALTER TABLE public.autores OWNER TO postgres;

--
-- TOC entry 219 (class 1259 OID 16389)
-- Name: autores_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.autores ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.autores_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 222 (class 1259 OID 16397)
-- Name: libros; Type: TABLE; Schema: public; Owner: postgres
--

CREATE TABLE public.libros (
    id bigint NOT NULL,
    descargas integer,
    idioma character varying(255),
    titulo character varying(255),
    autor_id bigint
);


ALTER TABLE public.libros OWNER TO postgres;

--
-- TOC entry 221 (class 1259 OID 16396)
-- Name: libros_id_seq; Type: SEQUENCE; Schema: public; Owner: postgres
--

ALTER TABLE public.libros ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.libros_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- TOC entry 4913 (class 0 OID 16390)
-- Dependencies: 220
-- Data for Name: autores; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.autores (id, fallecimiento, nacimiento, nombre) FROM stdin;
1	1616	1547	Cervantes Saavedra, Miguel de
2	1898	1832	Carroll, Lewis
\.


--
-- TOC entry 4915 (class 0 OID 16397)
-- Dependencies: 222
-- Data for Name: libros; Type: TABLE DATA; Schema: public; Owner: postgres
--

COPY public.libros (id, descargas, idioma, titulo, autor_id) FROM stdin;
1	12499	es	Don Quijote	1
2	63687	en	Alice's Adventures in Wonderland	2
\.


--
-- TOC entry 4921 (class 0 OID 0)
-- Dependencies: 219
-- Name: autores_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.autores_id_seq', 2, true);


--
-- TOC entry 4922 (class 0 OID 0)
-- Dependencies: 221
-- Name: libros_id_seq; Type: SEQUENCE SET; Schema: public; Owner: postgres
--

SELECT pg_catalog.setval('public.libros_id_seq', 2, true);


--
-- TOC entry 4761 (class 2606 OID 16395)
-- Name: autores autores_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.autores
    ADD CONSTRAINT autores_pkey PRIMARY KEY (id);


--
-- TOC entry 4763 (class 2606 OID 16404)
-- Name: libros libros_pkey; Type: CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.libros
    ADD CONSTRAINT libros_pkey PRIMARY KEY (id);


--
-- TOC entry 4764 (class 2606 OID 16405)
-- Name: libros fkspm6r4x8iif19d9gjsrvwev65; Type: FK CONSTRAINT; Schema: public; Owner: postgres
--

ALTER TABLE ONLY public.libros
    ADD CONSTRAINT fkspm6r4x8iif19d9gjsrvwev65 FOREIGN KEY (autor_id) REFERENCES public.autores(id);


-- Completed on 2025-12-08 07:25:32

--
-- PostgreSQL database dump complete
--

\unrestrict qxITwQbuQFgGZY0a082R5ddrVe9JAgLq6sxm0WXdEDmHTaNDaG3NJVOaja5r422

